-- AlterTable
ALTER TABLE "Plan" ADD COLUMN "machineVideo" TEXT;
ALTER TABLE "Plan" ADD COLUMN "machineOnline" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Plan" ADD COLUMN "machineUptimeHours" DOUBLE PRECISION NOT NULL DEFAULT 8760;
ALTER TABLE "Plan" ADD COLUMN "machineOnlineSince" TIMESTAMP(3);
